name: reviewdog
on: [pull_request, workflow_dispatch]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          # golangci_lint_flags: '--exclude-use-default=false'
          go_version: '1.16'
          reporter: github-pr-check
          level: error