name: reviewdog
on: [pull_request, workflow_dispatch]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: '--presets bugs,comment,complexity,error,format,import,metalinter,module,performance,sql,style,test,unused'
          go_version: '1.16'
          filter_mode: file